version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8090:8090"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html  # 前端静态文件
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro  # Nginx配置
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    expose:
      - "8000"  # 只在内部网络暴露端口
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    environment:
      - CONFIG_PATH=/app/config/config.toml 